name: snowplow_flutter_tracker
description: A package for tracking Snowplow events in Flutter apps
version: 0.1.0
homepage: https://github.com/snowplow-incubator/snowplow-flutter-tracker
repository: https://github.com/snowplow-incubator/snowplow-flutter-tracker

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  http: ^0.13.4
  uuid: 3.0.5

flutter:
  plugin:
    platforms:
      android:
        package: com.snowplowanalytics.snowplow_flutter_tracker
        pluginClass: SnowplowFlutterTrackerPlugin
      ios:
        pluginClass: SnowplowFlutterTrackerPlugin
      web:
        pluginClass: SnowplowFlutterTrackerPluginWeb
        fileName: snowplow_flutter_tracker_plugin_web.dart

  assets:
    - packages/snowplow_flutter_tracker/assets/sp.js
