name: Build and Test
on: [push, pull_request]
jobs:
  build:
    name: Analyze and run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.8.0'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter format -n --set-exit-if-changed .
      - run: flutter test

  build-android:
    name: Integration tests on Android
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "11.x"

      # -- Micro --
      - name: Cache Micro
        id: cache-micro
        uses: actions/cache@v2
        with:
          path: micro.jar
          key: ${{ runner.os }}-micro

      - name: Get micro
        if: steps.cache-micro.outputs.cache-hit != 'true'
        run: curl -o micro.jar -L https://github.com/snowplow-incubator/snowplow-micro/releases/download/micro-1.1.2/snowplow-micro-1.1.2.jar

      - name: Run Micro in background
        run: java -jar micro.jar --collector-config example/tool/micro.conf --iglu example/tool/iglu.json &

      - name: Wait on Micro endpoint
        timeout-minutes: 2
        run: while ! nc -z '0.0.0.0' 9090; do sleep 1; done

      - name: Update endpoint for Micro
        run: perl -i -pe "s/^.*microEndpoint =\K.*/ \'http:\/\/0.0.0.0:9090\'\;/" example/integration_test/helpers.dart

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.8.0'
          channel: 'stable'

      - name: Run Flutter Driver tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: default
          arch: x86_64
          profile: Nexus 6
          working-directory: example
          script: |
            flutter drive --driver test_driver/integration_test.dart --target integration_test/configuration_test.dart
            flutter drive --driver test_driver/integration_test.dart --target integration_test/events_test.dart
            flutter drive --driver test_driver/integration_test.dart --target integration_test/session_test.dart

  build-ios:
    name: Integration tests on iOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      # -- Micro --
      - name: Cache Micro
        id: cache-micro
        uses: actions/cache@v2
        with:
          path: micro.jar
          key: ${{ runner.os }}-micro

      - name: Get micro
        if: steps.cache-micro.outputs.cache-hit != 'true'
        run: curl -o micro.jar -L https://github.com/snowplow-incubator/snowplow-micro/releases/download/micro-1.1.2/snowplow-micro-1.1.2.jar

      - name: Run Micro in background
        run: java -jar micro.jar --collector-config example/tool/micro.conf --iglu example/tool/iglu.json &

      - name: Wait on Micro endpoint
        timeout-minutes: 2
        run: while ! nc -z '0.0.0.0' 9090; do sleep 1; done

      - name: Update endpoint for Micro
        run: perl -i -pe "s/^.*microEndpoint =\K.*/ \'http:\/\/10.0.2.2:9090\'\;/" example/integration_test/helpers.dart

      - name: "Start Simulator"
        uses: futureware-tech/simulator-action@v1
        with:
          model: iPhone 13
          erase_before_boot: true
          shutdown_after_job: true

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.8.0'
          channel: 'stable'

      - run: "flutter clean"

      - name: Run tests
        working-directory: example
        run: |
          flutter drive --driver test_driver/integration_test.dart --target integration_test/configuration_test.dart
          flutter drive --driver test_driver/integration_test.dart --target integration_test/events_test.dart
          flutter drive --driver test_driver/integration_test.dart --target integration_test/session_test.dart

  build-web:
    name: Integration tests on Web
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      # -- Micro --
      - name: Cache Micro
        id: cache-micro
        uses: actions/cache@v2
        with:
          path: micro.jar
          key: ${{ runner.os }}-micro

      - name: Get micro
        if: steps.cache-micro.outputs.cache-hit != 'true'
        run: curl -o micro.jar -L https://github.com/snowplow-incubator/snowplow-micro/releases/download/micro-1.1.2/snowplow-micro-1.1.2.jar

      - name: Run Micro in background
        run: java -jar micro.jar --collector-config example/tool/micro.conf --iglu example/tool/iglu.json &

      - name: Wait on Micro endpoint
        timeout-minutes: 2
        run: while ! nc -z '0.0.0.0' 9090; do sleep 1; done

      - name: Update endpoint for Micro
        run: perl -i -pe "s/^.*microEndpoint =\K.*/ \'http:\/\/0.0.0.0:9090\'\;/" example/integration_test/helpers.dart

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.8.0'
          channel: 'stable'

      - run: chromedriver --port=4444 &

      - name: Run tests
        working-directory: example
        run: ./tool/ci_script.sh web-server
