name: Publish package to pub.dev
on:
  push:
    branches:   
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: google/dart:latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup credentials
      run: | 
        mkdir -p ~/.pub-cache 
        cat <<EOF > ~/.pub-cache/credentials.json
        {
          "accessToken":"${{ secrets.ACCESS_TOKEN }}",
          "refreshToken":"${{ secrets.REFRESH_TOKEN }}",
          "tokenEndpoint":"https://accounts.google.com/o/oauth2/token",
          "scopes": [ "openid", "https://www.googleapis.com/auth/userinfo.email" ],
          "expiration": 1643122520446
        }
        EOF
    - name: Publish package
      run: pub publish -f
